### ISSUE TITLE
ubuntu or debian? php7.4 dependency

### ISSUE THREAD

**Issue by somethingGoneWrong** [edwardsj9090/firefly-iii-automation#1]
hi, i am on debian stable [10.9] and for [install php7.4 and php7.4-* pkgs](https://github.com/edwardsj9090/firefly-iii-automation/blob/12e9324967c7bf6a60566e3f59c569d65a71b7c3/installlampwithfirefly.sh#L18) i need to add external repo, like sury, it's not a big problem, but adding a small note about it in the readme would improve the procedure.
thx

**Comment by edwardsj9090** [comment]
@somethingGoneWrong I will work on the documentation for this and add it.  Thanks for the feedback :)

**Comment by edwardsj9090** [comment]
> 
> 
> hi, i am on debian stable [10.9] and for [install php7.4 and php7.4-* pkgs](https://github.com/edwardsj9090/firefly-iii-automation/blob/12e9324967c7bf6a60566e3f59c569d65a71b7c3/installlampwithfirefly.sh#L18) i need to add external repo, like sury, it's not a big problem, but adding a small note about it in the readme would improve the procedure.
> thx

Added :)

**Comment by edwardsj9090** [comment]
Added :)
