### ISSUE TITLE
question on folder permissions and then php warnings

### ISSUE THREAD

**Issue by cbounds89** [edwardsj9090/firefly-iii-automation#2]
Hey thanks for putting this together.  I'm new to linux and Pi

When I get "Change firefly-iii directory permissions" is it referring to the folder  '/var/www/firefly-ii'? 
the issue for me is the folder can't be there before running the .sh. if it is it errors out. so I have to delete the file every time I rerun it. 
How can I change the permissions on a folder that isn't there yet?

then when it gets down to the "artisan setup"
I get a bunch of PHP warnings. 
`PHP Warning:  require(/var/www/html/firefly-iii/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/firefly-iii/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/firefly-iii/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/firefly-iii/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/firefly-iii/artisan on line 18
PHP Warning:  require(/var/www/html/firefly-iii/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/firefly-iii/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/firefly-iii/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/firefly-iii/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/firefly-iii/artisan on line 18
PHP Warning:  require(/var/www/html/firefly-iii/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/firefly-iii/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/firefly-iii/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/firefly-iii/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/firefly-iii/artisan on line 18
PHP Warning:  require(/var/www/html/firefly-iii/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/firefly-iii/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/firefly-iii/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/firefly-iii/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/firefly-iii/artisan on line 18`

This is beyond me as of now.

any help is appreciated. 

Thank you!

**Comment by cbounds89** [comment]
IF I do delete the dir in /var/www/html I get a new set of errors
I did update composer and it said it was the latest version. 
`Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - diglactic/laravel-breadcrumbs is locked to version v6.0.2 and an update of this package was not requested.
    - diglactic/laravel-breadcrumbs v6.0.2 requires php ^7.2 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 2
    - laravel/passport is locked to version v10.0.1 and an update of this package was not requested.
    - laravel/passport v10.0.1 requires php ^7.3 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 3
    - lcobucci/jwt is locked to version 3.3.3 and an update of this package was not requested.
    - lcobucci/jwt 3.3.3 requires php ^5.6 || ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 4
    - league/csv is locked to version 9.6.1 and an update of this package was not requested.
    - league/csv 9.6.1 requires php ^7.2.5 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 5
    - pragmarx/recovery is locked to version v0.1.0 and an update of this package was not requested.
    - pragmarx/recovery v0.1.0 requires php ~7.0 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 6
    - tightenco/collect is locked to version v8.0.4 and an update of this package was not requested.
    - tightenco/collect v8.0.4 requires php ^7.1.3 -> your php version (8.0.8) does not satisfy that requirement.
  Problem 7
    - tightenco/collect v8.0.4 requires php ^7.1.3 -> your php version (8.0.8) does not satisfy that requirement.
    - adldap2/adldap2 v10.3.1 requires tightenco/collect ~5.0|~6.0|~7.0|~8.0 -> satisfiable by tightenco/collect[v8.0.4].
    - adldap2/adldap2 is locked to version v10.3.1 and an update of this package was not requested.
`

**Comment by edwardsj9090** [comment]
@cbounds89 Yes, when you get the _"Change firefly-iii directory permissions"_ message, it is referring to the _firefly-iii_ folder.  You do not have to do anything.  The script changes the permissions for you.

![image](https://user-images.githubusercontent.com/10908289/127484303-ba09e741-0193-41fc-9031-64d0df78ad05.png)

The order of operations:
1. The _git_ command downloads my auto installer to your user directory
2. You run the installlampwithfirefly.sh script (**not** as sudo or root), and it does the rest.  It installs Apache, MySQL, PHP, and then changes to the _/var/www/html_ directory and installs and runs **Composer** which calls down the firefly-iii project to the _html_ folder.  It then changes the permissions on the firefly-iii folder that Composer created.

NOTE: Be sure that composer does its job correctly or else you could end up with a corrupted/unfinished firefly-iii folder.

**Comment by edwardsj9090** [comment]
@cbounds89 Were you able to resolve the issue?  You most likely need to install the _sury_ repository.  That is what I had to do on the RPi as well to get php 7.4 to install since that is the version firefly iii requires.

**Comment by cbounds89** [comment]
@edwardsj9090 hey, that’s for checking but I did not.
 I ran the commands for sury but kept getting errors when it would set up artisan. 
I can’t remember the exact error but something in the .ini files for php. I doubled checked I had all the php modules installed.

**Comment by edwardsj9090** [comment]
@cbounds89 Make sure that the _/var/www/html_ directory exists.  I made the mistake the other day of accidentally deleting it and it does not come back upon re-run of the script or re-installation of apache.

I will run this on my clean RPi 3 and report back shortly.

**Comment by cbounds89** [comment]
I know that directory exists. As I have NextCloud running. 

i did delete the /firefly-iii directory in case it already existing causes any issues. I’ve done it with it there and after I delete it. 

I tried on my Ubuntu VM with no luck but can’t remember what happened exactly. 

Thanks for your help I really do appreciate it.

**Comment by edwardsj9090** [comment]
@cbounds89 I just now ran it on my Ubuntu VM as well with no issue.  I will try on the Pi shortly.

**Comment by edwardsj9090** [comment]
@cbounds89 So I ran it on my Pi 3 and my ubuntu server VM and both worked fine.

Try this:

`cd` (to get back to your default home directory)

`sudo rm -rf /var/www/html/firefly-iii` (to remove firefly-iii directory from web server)

`sudo rm -rf $HOME/firefly-iii-automation` (remove my automation folder from your home directory)

`sudo apt autoremove --purge apache2 mysql-* mariadb-* php7.4-* -y` (remove all web components)

**Comment by edwardsj9090** [comment]
@cbounds89 As far as the Artisan setup goes, that relies on PHP, so I'm wondering if the cleanup will work to wipe PHP off so you can re-install using the script.

**Comment by edwardsj9090** [comment]
![image](https://user-images.githubusercontent.com/10908289/127914989-7e8b3bf5-63f2-431c-9cc8-3e075c6fe30f.png)

![image](https://user-images.githubusercontent.com/10908289/127915054-9fc4f055-6523-47d6-9d8b-9c5e77fca420.png)

( Just press _Enter_ )
![image](https://user-images.githubusercontent.com/10908289/127915121-7b46187b-6fd9-41aa-9ca2-22e00826cac1.png)

![image](https://user-images.githubusercontent.com/10908289/127915264-fa197af2-d6c2-4a9b-bf8f-72a630fe6ee8.png)

**Comment by cbounds89** [comment]
Will running this code mess up next cloud settings? 

> sudo apt autoremove --purge apache2 mysql-* mariadb-* php7.4-* -y (remove all web components)

**Comment by cbounds89** [comment]
Thanks again for all this. Excited to try it when I get home in a few hours.

**Comment by edwardsj9090** [comment]
> 
> 
> Will running this code mess up next cloud settings?
> 
> > sudo apt autoremove --purge apache2 mysql-* mariadb-* php7.4-* -y (remove all web components)

Great question....so yes.  I forgot you are running NextCloud on the Pi as well.  The only true dependency for this whole thing to work _(composer and artisan are what basically build the project)_ is the installation of the proper PHP version and modules that the creator states in their documentation.  Which is why I have the script installing _php7.4-*_ so that way it grabs php 7.4 and all of the modules.

**Comment by edwardsj9090** [comment]
@cbounds89 If you could capture and post some screenshots of the installation in progress like I did above, that would help as well :)

**Comment by cbounds89** [comment]
Should I copy the directory for NextCloud in /var/www/html and move it? Or would that not doing anything?

**Comment by edwardsj9090** [comment]
So that would just backup your NextCloud folder which my cleanup script wouldn't touch anyway.  The NextCloud folder would remain, but all the web components would still be removed so you would just have a NextCloud folder with the files in it without a web service to access it.

**Comment by cbounds89** [comment]
Honestly that’s not an issue. Just a backup of phone photos that I can figure out after this gets set up.

**Comment by edwardsj9090** [comment]
@cbounds89 It's up to you ;)

Oh also after you run the cleanup, and re-run through my setup, try restarting the apache web service:

`sudo systemctl restart apache2`

I was downloading and installing NextCloud just now just for fun to test the install and after I installed the required PHP modules, I had to restart the web service.  I guess I'll write a script for NextCloud as well, as it requires slightly different PHP modules :)

**Comment by cbounds89** [comment]
alright. that didnt work. lol 


Everything was going good but I saw this line of code say it failed.
<img width="814" alt="Screen Shot 2021-08-02 at 7 31 53 PM" src="https://user-images.githubusercontent.com/18522116/127939866-23b85fa4-1ef6-4ac0-88ca-afff3e778b16.png">


here's everything after that as well
<img width="814" alt="Screen Shot 2021-08-02 at 7 32 19 PM" src="https://user-images.githubusercontent.com/18522116/127939910-9b52084b-16ab-441f-bf0e-a5bcb31ac742.png">

then it asks for my root. I hit enter.
then it asks for the root mysql password I hit enter. 
then.
<img width="814" alt="Screen Shot 2021-08-02 at 7 32 37 PM" src="https://user-images.githubusercontent.com/18522116/127939947-97784680-c96f-49bb-8c55-b5340f7b6151.png">

then the same errors under the Artisan setup.

**Comment by edwardsj9090** [comment]
@cbounds89 Ah I see.  Sorry didn't look close enough earlier lol.  Looks like php is too new.  Try uninstalling that first.  My script only cleans up version 7.x the nre-running everything.

![image](https://user-images.githubusercontent.com/10908289/127941107-f43f1e64-ca5f-4896-a3e9-fcea72af5752.png)

**Comment by cbounds89** [comment]
stand by! lol.

**Comment by cbounds89** [comment]
we're getting there!
<img width="1076" alt="Screen Shot 2021-08-02 at 8 13 54 PM" src="https://user-images.githubusercontent.com/18522116/127942449-56137cdd-c2e5-4eb8-909a-2815e9dbbe54.png">
<img width="1316" alt="Screen Shot 2021-08-02 at 8 14 15 PM" src="https://user-images.githubusercontent.com/18522116/127942458-b0723337-1f5b-4567-bee9-a7ddff14c139.png">

**Comment by cbounds89** [comment]
after I hit enter for the root mysql password. this line was next
"ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"

**Comment by edwardsj9090** [comment]
@cbounds89 

Ok so try the cleanup then re-run the install again.  I changed the script to install mariadb instead of mysql (interchangeable).

**Comment by cbounds89** [comment]
im also trying this. I found some instances of PHP still running. https://medium.com/@alef.duarte/cant-connect-to-local-mysql-server-through-socket-var-run-mysqld-mysqld-sock-155d580f3a06

**Comment by cbounds89** [comment]
that didnt work. I'll just wipe this PI there's nothing on it. and try again this weekend. Ill report back. 

I can't even get mysql to start up.

**Comment by edwardsj9090** [comment]
@cbounds89 Sorry this hasn't helped so far.  But yeah I was going to suggest wiping the pi.

After you get the OS back on there, just follow the instructions in the repo again and see if everything installs.

**Comment by cbounds89** [comment]
you have helped me a ton! I feel like im better at understanding whats happening and how to pick out the errors and go from there.  just gotta keep googling :)

**Comment by edwardsj9090** [comment]
@cbounds89 Yeah all of those php errors you're seeing as well as the artisan issues are all due to php version.  You should be able to successfully get this installed after a fresh Pi install and should be able to get NextCloud running on that same 7.4 php version as well.

**Comment by edwardsj9090** [comment]
@cbounds89 I ended up creating a nextcloud automation repo too lol.

**Comment by edwardsj9090** [comment]
@cbounds89 Don't forget when you re-image your RPi, to include the first part of the documentation for adding the _sury_ repo to your apt sources list.  This is what will allow you to install php7.4.

**Comment by cbounds89** [comment]
got it running. got a user created, added a bank and a savings. I went to edit the savings account name then got this error. 
where do I find the storage/logs?
<img width="1078" alt="Screen Shot 2021-08-03 at 6 43 14 PM" src="https://user-images.githubusercontent.com/18522116/128099942-611069a8-f94c-4c27-839d-fd2561c5fe32.png">

**Comment by cbounds89** [comment]
well that's been fixed. I ran your nextcloud repo and got that up and running! Thank you. (im thinking something in there changed a permission setting?)

**Comment by edwardsj9090** [comment]
@cbounds89 Oh ok so everything is up and running now? Yeah the only permission change I have in my code (from what I can remember) is `sudo chown -R www-data: foldername` for giving the apache service user ownership of the web folders under _/var/www/html_.

**Comment by cbounds89** [comment]
Yep all good now! Thank you so much:)

**Comment by edwardsj9090** [comment]
@cbounds89 Anytime :)
